{
 "title": "Body Measurements",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Weight",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_date::timestamptz AS \"time\",\n  user_id::text              AS series,\n  weight::double precision   AS value\nFROM body_measurements.bodyweight\nWHERE $__timeFilter(measure_date::timestamptz)\nORDER BY \"time\", series;"
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_date::timestamptz AS \"time\",\n  user_id::text              AS series,\n  weight::double precision   AS value\nFROM body_measurements.bodyweight\nWHERE $__timeFilter(measure_date::timestamptz)\nORDER BY \"time\", series;"
    }
   ]
  },
  {
   "title": "BF",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_date::timestamptz AS \"time\",\n  user_id::text              AS series,\n  bodyfat_percent::double precision   AS value\nFROM body_measurements.v_bodyfat_3site_men\nWHERE $__timeFilter(measure_date::timestamptz)\nORDER BY \"time\", series;"
    }
   ]
  },
  {
   "title": "BF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_date::timestamptz AS \"time\",\n  user_id::text              AS series,\n  bodyfat_percent::double precision   AS value\nFROM body_measurements.v_bodyfat_3site_men\nWHERE $__timeFilter(measure_date::timestamptz)\nORDER BY \"time\", series;"
    }
   ]
  },
  { "title": "Body", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Chest Circumference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", chest_circumference from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Thigh Circumference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", thigh_circumference from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Forearm Circumference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", forearm_circumference from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Waist Circumference",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", waist_circumference from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Chest Fold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", chest_fold from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Abdomen Fold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", abdomen_fold from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Thigh Fold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", thigh_fold from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Biceps Circumference",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", biceps_circumference from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  {
   "title": "Thigh Fold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select measure_date as \"time\", thigh_fold from body_measurements.body_measurements order by time asc"
    }
   ]
  },
  { "title": "Estimated 1RM Epley", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Bench Press",
   "type": "stat",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'BENCH_PRESS' ORDER BY time ASC "
    }
   ]
  },
  {
   "title": "French Press",
   "type": "stat",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'FRENCH_PRESS' ORDER BY time asc"
    }
   ]
  },
  {
   "title": "Squat",
   "type": "stat",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'SQUAT' ORDER BY time asc"
    }
   ]
  },
  {
   "title": "OHP",
   "type": "stat",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'OHP' ORDER BY time asc"
    }
   ]
  },
  {
   "title": "Biceps Curl Barbell",
   "type": "stat",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'BICEPS_CURL_BARBELL' ORDER BY time asc"
    }
   ]
  },
  {
   "title": "Lateral Raise",
   "type": "stat",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'LATERAL_RAISE' order by time asc"
    }
   ]
  },
  {
   "title": "Biceps Curl Dumbbells",
   "type": "stat",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'BICEPS_CURL_DUMBBELLS' order by time asc"
    }
   ]
  }
 ]
}