{
 "title": "Training Stats",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Estimated 1RM Epley", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bench Press",
   "type": "timeseries",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'BENCH_PRESS'"
    }
   ]
  },
  {
   "title": "French Press",
   "type": "timeseries",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'FRENCH_PRESS'"
    }
   ]
  },
  {
   "title": "Squat",
   "type": "timeseries",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'SQUAT'"
    }
   ]
  },
  {
   "title": "OHP",
   "type": "timeseries",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'OHP'"
    }
   ]
  },
  {
   "title": "Biceps Curl Dumbbells",
   "type": "timeseries",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'BICEPS_CURL_DUMBBELLS'"
    }
   ]
  },
  {
   "title": "Lateral Raise",
   "type": "timeseries",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'LATERAL_RAISE'"
    }
   ]
  },
  {
   "title": "Biceps Curl Barbell",
   "type": "timeseries",
   "description": "Estimated 1RM Epley",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", est_1rm_epley from trainings.v_session_exercise_metrics where exercise_name = 'BICEPS_CURL_BARBELL'"
    }
   ]
  },
  { "title": "Total Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bench Press",
   "type": "timeseries",
   "description": "Total Volume",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", total_volume \nfrom trainings.v_session_exercise_metrics\nwhere exercise_name = 'BENCH_PRESS'"
    }
   ]
  },
  {
   "title": "French Press",
   "type": "timeseries",
   "description": "Total Volume",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", total_volume \nfrom trainings.v_session_exercise_metrics\nwhere exercise_name = 'FRENCH_PRESS'"
    }
   ]
  },
  {
   "title": "Squat",
   "type": "timeseries",
   "description": "Total Volume",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", total_volume \nfrom trainings.v_session_exercise_metrics\nwhere exercise_name = 'SQUAT'"
    }
   ]
  },
  {
   "title": "OHP",
   "type": "timeseries",
   "description": "Total Volume",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", total_volume \nfrom trainings.v_session_exercise_metrics\nwhere exercise_name = 'OHP'"
    }
   ]
  },
  {
   "title": "Biceps Curl Dumbbells",
   "type": "timeseries",
   "description": "Total Volume",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", total_volume \nfrom trainings.v_session_exercise_metrics\nwhere exercise_name = 'BICEPS_CURL_DUMBBELLS'"
    }
   ]
  },
  {
   "title": "Lateral Raise",
   "type": "timeseries",
   "description": "Total Volume",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", total_volume \nfrom trainings.v_session_exercise_metrics\nwhere exercise_name = 'LATERAL_RAISE'"
    }
   ]
  },
  {
   "title": "Biceps Curl Barbell",
   "type": "timeseries",
   "description": "Total Volume",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "select session_date as \"time\", total_volume \nfrom trainings.v_session_exercise_metrics\nwhere exercise_name = 'BICEPS_CURL_BARBELL'"
    }
   ]
  },
  { "title": "Weekly Tonnage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Bench Press",
   "type": "barchart",
   "description": "Weekly Tonnage",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tweek_start as \"time\",\n\tweekly_tonnage\n\tFROM trainings.v_weekly_tonnage\n\twhere exercise_name = 'BENCH_PRESS';"
    }
   ]
  },
  {
   "title": "French Press",
   "type": "barchart",
   "description": "Weekly Tonnage",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tweek_start as \"time\",\n\tweekly_tonnage\n\tFROM trainings.v_weekly_tonnage\n\twhere exercise_name = 'FRENCH_PRESS';"
    }
   ]
  },
  {
   "title": "OHP",
   "type": "barchart",
   "description": "Weekly Tonnage",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tweek_start as \"time\",\n\tweekly_tonnage\n\tFROM trainings.v_weekly_tonnage\n\twhere exercise_name = 'OHP';"
    }
   ]
  },
  {
   "title": "Squat",
   "type": "barchart",
   "description": "Weekly Tonnage",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tweek_start as \"time\",\n\tweekly_tonnage\n\tFROM trainings.v_weekly_tonnage\n\twhere exercise_name = 'SQUAT';"
    }
   ]
  },
  {
   "title": "Biceps Curl Barbell",
   "type": "barchart",
   "description": "Weekly Tonnage",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tweek_start as \"time\",\n\tweekly_tonnage\n\tFROM trainings.v_weekly_tonnage\n\twhere exercise_name = 'BICEPS_CURL_BARBELL';"
    }
   ]
  },
  {
   "title": "Biceps Curl Dumbbells",
   "type": "barchart",
   "description": "Weekly Tonnage",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tweek_start as \"time\",\n\tweekly_tonnage\n\tFROM trainings.v_weekly_tonnage\n\twhere exercise_name = 'BICEPS_CURL_DUMBBELLS';"
    }
   ]
  },
  {
   "title": "Lateral Raise",
   "type": "barchart",
   "description": "Weekly Tonnage",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "rawSql": "SELECT \n\tweek_start as \"time\",\n\tweekly_tonnage\n\tFROM trainings.v_weekly_tonnage\n\twhere exercise_name = 'LATERAL_RAISE';"
    }
   ]
  }
 ]
}