apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 6.9.4
      helm:
        releaseName: argocd
        valueFiles:
          - $values/argocd/argocd/values-argocd.yaml
    - repoURL: https://github.com/kamil-kazmierczak/k8s-manifests
      targetRevision: develop
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]


