apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: db-tools
spec:
  type: NodePort
  selector:
    app: pgadmin4
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30432
