apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gethomepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: 2.1.0
    helm:
      values: |
        service:
          type: ClusterIP
          port: 3000
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: homepage.homelab.lan
              paths:
                - path: /
                  pathType: Prefix
          tls: []
  destination:
    server: https://kubernetes.default.svc
    namespace: gethomepage
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true" ]

