apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gethomepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: 2.1.0        # np. najnowsze wydanie z repo
    helm:
      valueFiles: [values.yaml]  # plik obok
  destination:
    server: https://kubernetes.default.svc
    namespace: gethomepage
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true" ]

