apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gethomepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: 2.1.0
    helm:
      values: |
        service:
          main:
            ports:
              http:
                port: 3000

        ingress:
          main:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: homepage.homelab.lan
                paths:
                  - path: /
                    pathType: Prefix
            tls: []  # zostaw puste, jeśli bez HTTPS

        env:
          HOMEPAGE_ALLOWED_HOSTS: "homepage.homelab.lan"

        config:
          services:
            - Apps:
                - Mikrotik:
                    icon: mikrotik-light.png
                    href: http://mikrotik.homelab.lan
                    description: RouterOS 7 by Mikrotik
                - Grafana:
                    icon: grafana.png
                    href: http://grafana.homelab.lan
                    description: Monitoring dashboards
                - pgAdmin:
                    icon: pgadmin.png
                    href: http://pgadmin.homelab.lan
                    description: Database management
                - Docmost:
                    icon: docmost.png
                    href: http://192.168.88.20:3001
                    description: Documentation
                - Proxmox VE:
                    icon: proxmox.png
                    href: https://192.168.88.10:8006
                    description: Virtualization and LXC
                - Portainer:
                    icon: portainer.png
                    href: https://192.168.88.20:9443
                    description: Docker management
                - Argo CD:
                    icon: argo-cd.png
                    href: https://192.168.88.21:30081
                    description: GitOps cluster management

  destination:
    server: https://kubernetes.default.svc
    namespace: gethomepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

