apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gethomepage
  namespace: argocd
spec:
  project: default
  sources:
    # Twoje repo z dodatkowymi plikami
    - repoURL: https://github.com/kamil-kazmierczak/k8s-manifests
      targetRevision: develop
      path: helm-apps/gethomepage
      ref: repo

    # Helm chart homepage
    - repoURL: https://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: 2.1.0
      helm:
        valueFiles:
          - $repo/values.yaml   # wskazuje na values.yaml w tym katalogu
  destination:
    server: https://kubernetes.default.svc
    namespace: gethomepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

