apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gethomepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: 2.1.0
    helm:
      values: |
        service:
          main:
            ports:
              http:
                port: 3000

        ingress:
          main:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: homepage.homelab.lan
                paths:
                  - path: /
                    pathType: Prefix
            tls: []  # zostaw puste, jeśli bez HTTPS

        env:
          HOMEPAGE_ALLOWED_HOSTS: "homepage.homelab.lan"

        config:
          services:
            - Grafana:
              icon: si:grafana
              href: http://grafana.homelab.lan
              description: Monitoring dashboards
            - pgAdmin:
              icon: si:postgresql
              href: http://pgadmin.homelab.lan
              description: Database management

  destination:
    server: https://kubernetes.default.svc
    namespace: gethomepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

