apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gethomepage
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kamil-kazmierczak/k8s-manifests
      targetRevision: develop
      path: helm-apps/gethomepage    # tu leży Twój values.yaml + configmap.yaml
      ref: values                    # <<< NAZWA referencji

    - repoURL: https://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: 2.1.0
      helm:
        valueFiles:
          - $values/values.yaml      # <<< UŻYJ ref: $values
  destination:
    server: https://kubernetes.default.svc
    namespace: gethomepage
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ "CreateNamespace=true" ]

