apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  commonName: grafana.homelab.lan
  dnsNames:
    - grafana.homelab.lan
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer

