apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls
  commonName: vaultwarden.homelab.lan
  dnsNames:
    - vaultwarden.homelab.lan
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer

